### ISSUE TITLE
Credit Where Due

### ISSUE THREAD

**Issue by MotoAcidic** [SexyCamCrypto/SexyCam#1]
You need to give credit to the Abet team for developing this banner in your wallet since you did not develop this but rather copy pasted it.
https://github.com/SexyCamCrypto/SexyCam/blob/2e213f94695ec998f49b3db2a807a6870305756c/src/qt/bitcoingui.cpp#L582

**Comment by SexyCamCrypto** [comment]
Issue fixed by commit/174e6d3d359ed5e3d8666cb189c4ff682ec4a88b
